# Generated by Django 4.2.5 on 2023-11-14 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("members", "0002_friendmanager_delete_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="./static/images/default.jpeg",
                        upload_to="./static/images",
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "friends",
                    models.ManyToManyField(
                        related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="track",
            name="username",
        ),
        migrations.DeleteModel(
            name="FriendManager",
        ),
        migrations.AddField(
            model_name="profile",
            name="tracks",
            field=models.ManyToManyField(to="members.track"),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="username",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
